version: "3.8"

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: anime_db
      MYSQL_USER: tyson
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_db:/var/lib/mysql
    ports:
      - '3308:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: anime_db
      MYSQL_USER: tyson
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '5000:80'
    depends_on:
      db:
        condition: service_healthy

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    volumes:
      - "./airflow:/root/airflow/"
    environment:
      MYSQL_HOST: db_host
      MYSQL_DATABASE: anime_db
      MYSQL_USER: tyson
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:8080'
    depends_on:
      - db
      - app