FROM python:3.9

#spin up airflow

WORKDIR /root
COPY ./requirements_airflow.txt requirements_airflow.txt
RUN pip install -r requirements_airflow.txt
RUN pip install apache-airflow
CMD ["airflow", "standalone"]

