# name: Run Python Tests
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# defaults:
#       run:
#         shell: bash

#     steps:
#     - name: Check out repository code
#       uses: actions/checkout@v2

#     - name: Setup Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: "3.8"

#     - name: Test API
#     run: |
#     - name: Run tests with pytest
#       run: python app.test_app.py